export const INITIAL_CLIENTS = [
    "Aaicho Paicho Cooperative",
    "B.G Nepal Pvt Ltd",
    "Cathay Pacific",
    "CG Agro",
    "CG Digicom",
    "CG Group Pvt. Ltd.",
    "Chhangyandi",
    "Coffee Abhyas",
    "Crystal Kanchanjunga Securities Pvt. Ltd",
    "EOS International",
    "EOS Venture",
    "Fisher & Pyaker Health Care India",
    "Galaxy Public School",
    "Garima Securities",
    "GCE Group Pvt.Ltd.",
    "Golden Harvest Farm Pvt.Ltd.",
    "Himal Media Pvt. Ltd.",
    "Hongkong Dragon",
    "IFES",
    "Imperial Securities Pvt. Ltd",
    "Jade Consult Pvt. Ltd.",
    "Jagadamba Press",
    "Karyabinayak",
    "Loom Nepal",
    "Lovely Co-operative",
    "Lower Erkhuwa Hydropower Company Ltd.",
    "Madan Puraskar Guthi",
    "Madan Puraskar Pustakalaya",
    "Malindo Air",
    "Martin Dairy Pvt. Ltd.",
    "Matrix Holdings Pvt Ltd",
    "Multi Hydro",
    "Namaste Supply Chain",
    "Narayani Machineries Pvt.Ltd",
    "Nepal Wellhope Agritech Pvt. Ltd.",
    "Nextgen Solution Pvt.Ltd",
    "Nextgen/Sastra JV",
    "Omega Energy Developers Pvt Ltd.",
    "Organic Venture Nepal",
    "Oxford Seccurities Pvt. Ltd",
    "PATAN DHOKA",
    "Peace Energy Co. Pvt ltd",
    "Peoples Energy",
    "PSP Consortium",
    "Purnima Projects Pvt. Ltd",
    "PWC Nepal",
    "Shakti Foods",
    "Shakti milan samaj",
    "Shakti Samuha",
    "Sharp Travels Pvt. Ltd.",
    "SHIP Nepal",
    "Single Tree Sky bridge glass pvt. Ltd",
    "South Asia Institute of History & Philosophy",
    "Stantec International",
    "Stock Brokers Association",
    "Sundhara Investment PVt.Ltd",
    "Sunshine Lasha",
    "Super Flex Pvt Ltd",
    "Tizig Pharma",
    "Thai Lion Airlines",
    "TPO Nepal",
    "Trans Himalaya",
    "Travel Desk",
    "United Remit Pvt.Ltd",
    "Upaya City cargo",
    "Upaya services",
    "Upaya Warehousing",
    "Upper Syange Hydropower Pvt. Ltd",
    "Vijay Motors",
    "Vision Energy Power Ltd.",
    "Watford hotel",
    "White Leaf Forest",
    "Yalamaya Dhokaima Café",
    "Zephyr Tours & Travels Pvt. Ltd"
];
