
export enum UserRole {
  MASTER_ADMIN = 'MASTER_ADMIN',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
  STAFF = 'STAFF'
}

export interface FocusGoal {
  id: string;
  text: string;
  completed: boolean;
}

export interface UserProfile {
  uid: string;
  email: string;
  displayName: string;
  role: UserRole;
  department: string;
  photoURL?: string;
  phoneNumber?: string;
  isSetupComplete?: boolean;
  isOnboardingComplete?: boolean;
  registeredAt?: string;
  registeredBy?: string;
  pendingWorkLogs?: WorkLog[];
  // Extended Fields for Staff Directory
  address?: string;
  dateOfJoining?: string;
  position?: string;
  status?: 'Active' | 'Inactive' | 'Pending Approval';
  gender?: 'Male' | 'Female' | 'Other';
  leaveAdjustment?: number; // Manual correction for leave balance
  taskCreationAuthorized?: boolean; // Granted by Master Admin: allows creating new tasks
  complianceCreationAuthorized?: boolean; // Granted by Master Admin: allows creating compliance events
  
  // User Preference
  theme?: 'light' | 'dark';
  
  // Session Security
  currentSessionId?: string;
  sessionCreatedAt?: number;

  // New: Persistent Dashboard State
  currentFocusGoals?: FocusGoal[];
}

export interface StaffDirectoryProfile {
  uid: string;
  displayName: string;
  email: string; // Official email is usually public within org
  role: UserRole;
  department: string;
  position?: string;
  phoneNumber?: string; // Optional, maybe business phone?
  status?: 'Active' | 'Inactive' | 'Pending Approval';
  photoURL?: string;
  gender?: 'Male' | 'Female' | 'Other';
  dateOfJoining?: string; // Often harmless, but can be omitted if super strict
}

export interface AttendanceRecord {
  id: string;
  userId: string;
  userName: string;
  date: string; // ISO Date YYYY-MM-DD
  clockIn: string; // ISO Timestamp
  clockOut?: string; // ISO Timestamp
  notes?: string; // Used for Late Reason or Admin correction notes
  location?: { lat: number; lng: number };
  status: 'PRESENT' | 'LATE' | 'HALF_DAY' | 'ABSENT' | 'CORRECTED' | 'ON LEAVE';
  workHours: number; // in hours
  // New Reporting Fields
  clientId?: string;
  clientName?: string;
  clientIds?: string[]; // Multiple clients
  workDescription?: string;
  workLogs?: WorkLog[]; // Detailed work breakdown
}

export interface AttendanceLogRequest extends Omit<AttendanceRecord, 'id'> {
  id: string;
  requestStatus: 'PENDING' | 'APPROVED' | 'REJECTED';
  adminNotes?: string;
  requestedAt: string;
}

export interface WorkLog {
  id: string;
  clientId: string;
  clientName: string;
  natureOfAssignment?: string; // New: Internal Audit, Statutory Audit, etc.
  description: string;
  duration: number;   // in hours
  billable: boolean;
  locationTag?: 'Office' | 'Client Premises';
}

export enum TaskStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  UNDER_REVIEW = 'UNDER_REVIEW',
  HALTED = 'HALTED',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED'
}

export enum AuditPhase {
  ONBOARDING = 'ONBOARDING',
  PLANNING_AND_EXECUTION = 'PLANNING_AND_EXECUTION',
  REVIEW_AND_CONCLUSION = 'REVIEW_AND_CONCLUSION'
}

export interface TaskStatusConfig {
  status: TaskStatus;
  label: string;
  color: string;
  isEmailEnabled?: boolean;
  emailTemplateId?: 'DEFAULT' | 'ASSIGNMENT' | 'STATUS_CHANGE' | 'URGENT_REMINDER';
  autoAssignTo?: string[];
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum TaskType {
  INTERNAL_AUDIT = 'INTERNAL_AUDIT',
  STATUTORY_AUDIT = 'STATUTORY_AUDIT',
  COMPLIANCE_AUDIT = 'COMPLIANCE_AUDIT',
  CERTIFICATION_SERVICE = 'CERTIFICATION_SERVICE',
  FINANCIAL_MANAGEMENT = 'FINANCIAL_MANAGEMENT',
  GENERAL = 'GENERAL',
  OTHER = 'OTHER',
}


export interface Attachment {
  id: string;
  name: string;
  url: string;
  type: 'FILE' | 'LINK';
}

export interface SubTask {
  id: string;
  title: string;
  minimumRequirement?: string; // e.g., "Check invoices > 10k"
  isCompleted: boolean;
  createdBy: string; // Name of user who added it
  createdAt: string;
  assignedTo?: string[]; // NEW: Specific staff members assigned to this checklist item
  phase?: AuditPhase; // NEW: Associate subtask directly to a phase
  isNew?: boolean; // NEW: For visual feedback (pulse)
  isAutoGenerated?: boolean; // NEW: For distinguishing from manual subtasks
  
  // Professional Audit Intelligence (Master Suite)
  reference?: string; // Annexure / ISA / IFRS / Law Ref
  sopUrl?: string; // Deep link to specific procedure manual segment
  isEvidenceMandatory?: boolean; // Compliance gate
  evidenceProvided?: boolean; // NEW: Has the staff uploaded/logged evidence?
  evidenceText?: string; // NEW: Free text reference (e.g. Voucher Number)
  queryStatus?: 'OPEN' | 'RESOLVED' | 'CLEARED'; // Review note workflow
  queryComment?: string; // Reviewer note
  queryReply?: string; // Staff response
  queryRaisedBy?: string; // UID
  queryRaisedAt?: string; // Timestamp
  addedBy?: string; // UID of the user who manually added this
  addedByName?: string; // Display name of the user who manually added this
}

// Audit folder key — defined here so Task interface can reference it
export type AuditFolderKey = 'A' | 'B' | 'C' | 'D' | 'E';

export interface Task {
  id: string;
  title: string;
  description: string;
  assignedTo: string[]; // Array of User UIDs
  assignedToNames: string[]; // Array of Names for display
  createdBy: string; // User UID
  clientId?: string; // DEPRECATED: Single client (kept for backward compatibility)
  clientIds?: string[]; // NEW: Multiple clients support
  clientName?: string;
  taskType?: TaskType; // Engagement type
  status: TaskStatus;
  priority: TaskPriority;
  startDate?: string;
  dueDate: string;
  estimatedDays?: number; // For Resource Planning
  driveFolderLink?: string;
  sopLink?: string;
  createdAt: string;
  completedAt?: string;
  attachments?: Attachment[];
  subtasks?: SubTask[];
  teamLeaderId?: string; // UID of the designated team leader
  riskLevel?: 'LOW' | 'MEDIUM' | 'HIGH';
  reviewStatus?: 'PENDING' | 'APPROVED' | 'REJECTED';
  comments?: TaskComment[];
  templateId?: string; // NEW: The ID of the template from which this task was created
  nextTemplateId?: string; // NEW: The ID of the template to trigger upon completion

  // Advanced Workflow Features (TaxDome-style)
  tags?: string[]; // Custom status/category tags
  totalTimeSpent?: number; // Total minutes logged on this task
  auditPhase?: AuditPhase; // The specific audit phase this task is currently under
  updatedAt?: string; // Added for engagement tracking
  linkedFolderId?: string; // NEW: The ID of the template folder powering the checklist
  engagementReviewerId?: string; // NEW: Assignment Team Leader / First Reviewer
  signingPartnerId?: string; // NEW: Signing Person / Final Reviewer
  teamLeadApprovedAt?: string; // NEW: Timestamp for Team Lead sign-off
  engagementReviewerApprovedAt?: string; // NEW: Timestamp for Engagement Reviewer sign-off
  signingPartnerApprovedAt?: string; // NEW: Timestamp for Final Partner sign-off
  
  // Archiving
  fiscalYear?: string;                // The Nepali Fiscal Year (e.g., "2080-81") assigned during creation
  archivedFiscalYear?: string;        // Metadata field for the year it was actually archived
  
  // Audit Master Suite (Observations & Findings)
  observations?: AuditObservation[];

  // ── Reviewer Checklists (populated from REVIEWER_CHECKLIST templates) ──
  reviewChecklist?: ReviewChecklistItem[];

  // Audit Documentation Tagging (for future NAS integration)
  auditFolderTag?: AuditFolderKey;   // Which audit folder this task maps to (A/B/C/D/E)
  auditLineItem?: string;            // Specific B-folder line item e.g. "B.3"
}

// ─── Audit Documentation System ──────────────────────────────────────────────


export interface AuditFolderDefinition {
  label: string;
  description: string;
  color: string;
  bgColor: string;
  borderColor: string;
  lineItems?: string[];
}

export const AUDIT_FOLDER_STRUCTURE: Record<AuditFolderKey, AuditFolderDefinition> = {
  A: {
    label: 'A. Initial Documents',
    description: 'Engagement letters, client KYC, prior year communications, planning documents',
    color: '#3b82f6',
    bgColor: 'rgba(59,130,246,0.10)',
    borderColor: 'rgba(59,130,246,0.25)',
  },
  B: {
    label: 'B. Docs Related to V&V of FS',
    description: 'Verification and validation working papers for each financial statement line item',
    color: '#8b5cf6',
    bgColor: 'rgba(139,92,246,0.10)',
    borderColor: 'rgba(139,92,246,0.25)',
    lineItems: [
      'B.1. Opening Checking',
      'B.2. PPE',
      'B.3. Investments',
      'B.4. Trade and Other Receivables',
      'B.5. Advance and Deposits',
      'B.6. Cash & Cash Equivalents',
      'B.7. Inventories',
      'B.8. Share Capital',
      'B.9. Long Term Loan',
      'B.10. Accounts and Other Payables',
      'B.11. Provision for Taxation',
      'B.12. Revenue',
      'B.13. Other Income',
      'B.14. Administrative Expense',
      'B.15. Finance Cost',
    ],
  },
  C: {
    label: 'C. Compliance Checking',
    description: 'Regulatory compliance documents, tax compliance, statutory requirements',
    color: '#f59e0b',
    bgColor: 'rgba(245,158,11,0.10)',
    borderColor: 'rgba(245,158,11,0.25)',
  },
  D: {
    label: 'D. Others',
    description: 'Miscellaneous working papers, internal memos, correspondence',
    color: '#10b981',
    bgColor: 'rgba(16,185,129,0.10)',
    borderColor: 'rgba(16,185,129,0.25)',
  },
  E: {
    label: 'E. Documents Related with Reporting',
    description: 'Draft reports, management letters, final audit reports, sign-off documents',
    color: '#ef4444',
    bgColor: 'rgba(239,68,68,0.10)',
    borderColor: 'rgba(239,68,68,0.25)',
  },
};

export type AuditDocumentStatus = 'LINKED' | 'PENDING' | 'NOT_APPLICABLE';

export interface AuditDocumentEntry {
  id: string;
  clientId: string;
  clientName: string;
  fiscalYear: string;           // e.g., "2081-82"
  folderKey: AuditFolderKey;
  lineItem?: string;            // e.g., "B.3" — only for folder B
  lineItemLabel?: string;       // e.g., "B.3. Investments"
  notes?: string;
  networkPath?: string;         // Future: UNC path \\SERVER\Clients\ClientName\FY\FolderKey
  status: AuditDocumentStatus;
  addedBy: string;              // User UID
  addedByName: string;          // Display name
  addedAt: string;              // ISO timestamp
  updatedAt?: string;
}

export interface AuditObservation {
  id: string;
  title: string;
  observation: string; // Condition
  implication: string; // Criteria / Risk
  recommendation: string; // Corrective Action
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  status: 'DRAFT' | 'OPEN' | 'IN_PROGRESS' | 'CLOSED';
  createdAt?: string;
  createdBy?: string;
  createdByName?: string;
}

export interface TaskComment {
  id: string;
  text: string;
  userId: string;
  userName: string;
  createdAt: string;
  mentions?: string[]; // userIds
}

export interface Client {
  id: string;
  name: string;
  businessName?: string; // Added for engagement tracking
  code: string;
  pan?: string;       // New from previous refactor
  phone?: string;     // New from previous refactor
  email?: string;     // New from previous refactor
  address?: string;   // New from previous refactor

  // Services / Types
  serviceType: 'Statutory Audit' | 'Tax Filing' | 'Compliance Audit' | 'Internal Audit' | 'Advisory Services' | 'Bookkeeping' | 'VAT Filing' | 'ITR Filing' | 'Other';
  industry: 'Airlines' | 'Consulting' | 'Co-operatives' | 'Courier' | 'Education' | 'Hotel & Restaurant' | 'Hydropower' | 'Investment' | 'IT Consulting' | 'Joint Venture' | 'Manufacturing' | 'NGO/INGO' | 'NPO' | 'Others' | 'Securities Broker' | 'Trading';
  category: 'A' | 'B' | 'C';
  status: 'Active' | 'Inactive' | 'Pending';

  // Tax & Compliance
  vatReturn?: boolean; // New: Needs VAT Return (Every Nepali 25th)
  itrReturn?: boolean; // New: Needs Income Tax Return

  // Management
  signingAuthorityId?: string; // UID of the signee (Partner/Manager)
  signingAuthority?: string; // Display Name (Partner/Manager)
  contactPerson?: string;
  contactPersonName?: string; // Added for engagement tracking
  contactPersonPhone?: string; // Added for engagement tracking
  contactPersonPan?: string; // Added for engagement tracking
  contactPersonRole?: string;

  // Billing (New)
  billingAmount?: number;
  paymentStatus?: 'Paid' | 'Pending' | 'Partial' | 'Overdue';

  // Management
  auditorId?: string;
  createdAt?: string;
  updatedAt?: string;

  // Nepal Specific Context (Statutory)
  registrationDate?: string; // BS or AD string
  vatNumber?: string;
  vdcMunicipality?: string;
  fiscalYearEnd?: string;

  // Knowledge Base / KYC Documents
  documents?: {
    id: string;
    title: string;
    url: string;
    category: 'KYC' | 'Legal' | 'Tax' | 'Audit' | 'Other';
    uploadedAt: string;
    uploadedBy: string;
  }[];

  // Risk & Audit Focus Areas (NEW)
  riskAreas?: RiskAreaDocument[];

  // Client Notes — rich text / plain text pasted by staff (NEW)
  clientNotes?: string;

  // Engagement Details (NEW)
  engagementLetterUrl?: string;
  auditPeriod?: string;          // e.g. "FY 2081-82" or "2024-25"
  auditStartDate?: string;       // ISO date
  auditEndDate?: string;         // ISO date

  // Billing Notes (NEW)
  billingNotes?: string;
}

export interface RiskAreaDocument {
  id: string;
  title: string;
  description?: string;          // Summary or notes about this risk area
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  category: 'Financial' | 'Compliance' | 'Operational' | 'Tax' | 'Regulatory' | 'Other';
  documentUrl?: string;          // Optional uploaded file URL
  documentName?: string;         // File name if uploaded
  status: 'OPEN' | 'MITIGATED' | 'MONITORING' | 'CLOSED';
  addedBy: string;               // User UID
  addedByName: string;           // Display name
  addedAt: string;               // ISO timestamp
  updatedAt?: string;
  focusPoints?: string[];        // Bullet-point critical areas to check
}

export interface StaffDetailStats {
  totalTasksAssigned: number;
  tasksCompleted: number;
  tasksOverdue: number;
  tasksInProgress: number;
  attendanceDaysThisMonth: number;
  lateArrivalsThisMonth: number;
  currentLeaveBalance: number;
  clientsAssigned: string[];     // Array of client names
}

export interface LeaveRequest {
  id: string;
  userId: string;
  userName: string;
  type: 'Sick' | 'Casual' | 'Annual' | 'Unpaid' | 'Exam' | 'Home' | 'Other';
  startDate: string;
  endDate: string;
  reason: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  rejectionReason?: string;
  createdAt: string;
}

// Event visibility levels
export type EventVisibility = 'PRIVATE' | 'PUBLIC' | 'TEAM' | 'DEPARTMENT';

// Event types
export type EventType = 'MEETING' | 'DEADLINE' | 'GENERAL' | 'PERSONAL' | 'FIRM_EVENT' | 'HOLIDAY';

// RSVP status
export type RSVPStatus = 'ACCEPTED' | 'DECLINED' | 'TENTATIVE';

// Recurrence rule for recurring events
export interface RecurrenceRule {
  frequency: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';
  interval: number; // Every X days/weeks/months/years
  endDate?: string; // When recurrence stops (YYYY-MM-DD)
  daysOfWeek?: number[]; // For weekly recurrence (0=Sunday, 6=Saturday)
}

// Event reminder configuration
export interface EventReminder {
  type: 'EMAIL' | 'IN_APP';
  minutesBefore: number; // Minutes before event to send reminder
}

// Enhanced CalendarEvent interface
export interface CalendarEvent {
  id: string;
  title: string;
  date: string; // YYYY-MM-DD
  time?: string; // HH:MM
  endTime?: string; // HH:MM (for duration)
  description?: string;
  type: EventType;

  // NEW: Event ownership and visibility
  createdBy: string; // User UID who created the event
  visibility: EventVisibility; // Who can see this event
  teamIds?: string[]; // For TEAM visibility - array of user UIDs
  department?: string; // For DEPARTMENT visibility

  // NEW: Recurring events
  isRecurring?: boolean;
  recurrenceRule?: RecurrenceRule;
  parentEventId?: string; // For instances of recurring events

  // NEW: Participants and RSVP
  participants?: string[]; // Array of user UIDs invited to event
  rsvpRequired?: boolean;
  rsvpResponses?: {
    [userId: string]: RSVPStatus;
  };

  // NEW: Reminders
  reminders?: EventReminder[];
  notifyOnEventDate?: boolean; // Send email/notifications only on the date fixed for the event
  scheduledNotificationDate?: string; // YYYY-MM-DD
  scheduledNotificationTime?: string; // HH:MM

  // NEW: Additional metadata
  color?: string; // Hex color for event category
  location?: string; // Physical or virtual location
  attachments?: string[]; // File URLs or references
  createdAt?: string; // ISO timestamp when created
  updatedAt?: string; // ISO timestamp when last modified
}

export interface AppNotification {
  id: string;
  userId: string; // The user who should see this notification
  title: string;
  message: string;
  type: 'WARNING' | 'INFO' | 'SUCCESS';
  category: 'TASK' | 'LEAVE' | 'EVENT' | 'SYSTEM' | 'ATTENDANCE';
  link?: string; // Optional navigation link (e.g., /tasks)
  read: boolean;
  createdAt: string; // ISO Timestamp
}

export interface Resource {
  id: string;
  title: string;
  type: 'folder' | 'pdf' | 'doc' | 'sheet' | 'article' | 'image';
  category: string; // Keep for legacy/filtering
  updatedAt: string;
  link?: string; // Optional for folders/articles
  url?: string; // Standardized link for UI
  content?: string; // HTML/Markdown for articles
  parentId?: string | null; // For hierarchy
  previewLink?: string;
  fileId?: string;
  downloadUrl?: string; // For documents that need direct download
  fileSize?: number; // File size in bytes
  createdBy?: string; // UID of the uploader
  createdByName?: string; // Display name of the uploader
  reviewDate?: string; // Expiry date for SOP verification
  tags?: string[]; // Custom tagging system (NFRS, VAT, etc.)
  isPinned?: boolean; // Pinned / Favourites section
  // Soft-delete / Recycle Bin
  isDeleted?: boolean;    // true = in trash
  deletedAt?: string;     // ISO timestamp of when moved to trash
  deletedBy?: string;     // UID of who trashed it
}

export interface TemplateFolder {
  id: string;
  name: string;
  description?: string;
  color?: string; // For UI display
  icon?: string;  // For UI display
  createdBy: string;
  createdAt: string;
  updatedAt?: string;
}

export interface TaskTemplate {
  id: string;
  name: string;
  description: string;
  folderId?: string; // NEW: Associate with a folder
  folderName?: string;
  priority: TaskPriority;
  category: 'TASK' | 'CHECKLIST' | 'DOCUMENT' | 'WORKFLOW' | 'SOP' | 'TEMPLATE' | 'REVIEWER_CHECKLIST';
  taskType?: TaskType;
  subtasks?: string[]; // Legacy array of strings for SOPs/Checklists
  subtaskDetails?: { 
    title: string; 
    minimumRequirement?: string; 
    assigneeRole?: UserRole | string; // NEW: Auto-assign user with this role
    daysOffset?: number; // NEW: Due date offset from anchor date
    phase?: AuditPhase; // NEW: Phase this subtask belongs to (for auto-generation)
    
    // Master Suite Framework Inheritance
    reference?: string;
    sopUrl?: string;
    isEvidenceMandatory?: boolean;
  }[]; // Enhanced subtasks
  expectedDays?: number;
  createdAt: string;
  updatedAt?: string;
  documentLink?: string;
  // Status-based automatic subtasks
  statusSubtasks?: {
    [key in TaskStatus]?: { title: string; minimumRequirement?: string; }[];
  };
  // Auto-Apply Rules
  autoApplyRules?: {
    industryType?: string;
    serviceType?: string; // e.g., Audit, Tax
  };
  // New fields for Template Library Upgrade
  attachments?: Attachment[];
  tags?: string[];
  isPublic?: boolean;
  usageCount?: number;
  type?: string;
  reviewerRole?: 'TL' | 'ER' | 'SP';
  content?: string;
  createdBy?: string;
  nextTemplateId?: string; // NEW: Trigger this template automatically when task completes
  reviewChecklist?: Partial<ReviewChecklistItem>[];
}

export type Template = TaskTemplate;

// ─── Reviewer Checklist Item (stored on Task) ───────────────────────────────
export interface ReviewChecklistItem {
  id: string;
  title: string;
  minimumRequirement?: string;
  status: 'OK' | 'ISSUE' | 'PENDING';
  priority: 'CRITICAL' | 'HIGH' | 'MEDIUM';
  notes?: string;
  wpRef?: string;
  comment?: string;
  isCompleted: boolean; // Keep for backward compat, but status is primary
  completedBy?: string; // UID
  completedByName?: string;
  completedAt?: string; // ISO timestamp
  reviewerRole: 'TL' | 'ER' | 'SP'; // Which reviewer layer owns this item
  templateId?: string; // Source template
  isSectionHeader?: boolean; // NEW: If true, this item acts as a category header
}

export interface Category {
  id: string;
  label: string;
  icon: string; // Helper to map to Lucide icons (e.g., 'Book', 'FileText')
  color?: string; // Hex or Tailwind class for styling
  createdAt: string;
}

// --- Performance Evaluation System Types ---

export interface ScoringComponents {
  completion_rate: number;
  on_time_delivery: number;
  punctuality: number;
  task_quality: number;
  task_difficulty: number;
}

export interface FinalizedPerformanceScore {
  user_id: string;
  user_name: string;
  total_score: number;
  rank: number;
  components: ScoringComponents;
  eligibility: {
    qualified: boolean;
    reason?: string;
    failed_criteria?: string[];
  };
}

export interface PerformanceCycle {
  id: string;
  tenant_id: string;
  month: string; // "2026-02"
  status: 'ACTIVE' | 'FINALIZED' | 'ARCHIVED';
  finalized_at: string; // ISO Timestamp
  staff_scores: Record<string, FinalizedPerformanceScore>;
  staff_of_month: {
    user_id: string;
    score: number;
    rank: 1;
    reason: string;
  };
  team_stats: {
    avg_score: number;
    median_score: number;
    total_tasks: number;
  };
}

export interface PerformanceGoal {
  id: string;
  user_id: string;
  month: string;
  metric: 'TOTAL_SCORE' | 'COMPLETION_RATE' | 'PUNCTUALITY' | 'ON_TIME_RATE';
  target: number;
  current: number;
  status: 'ON_TRACK' | 'AT_RISK' | 'OFF_TRACK';
  progress: number; // 0-100%
}

export interface Achievement {
  id: string;
  name: string;
  description: string;
  points: number;
  rarity: 'COMMON' | 'RARE' | 'EPIC' | 'LEGENDARY';
  icon: string;
  earnedAt?: string;
}

export interface PointsBreakdown {
  user_id: string;
  month: string;
  total_points: number;
  breakdown: {
    tasks_completed: number;
    early_completions: number;
    perfect_weeks: number;
    helping_others: number;
    learning_activities: number;
    zero_late_days: number;
  };
}

export interface Streaks {
  user_id: string;
  perfect_days: {
    current: number;
    longest: number;
    started_at: string;
  };
  on_time_tasks: {
    current: number;
    longest: number;
  };
  zero_late_attendance: {
    current: number;
    longest: number;
  };
}

export interface PeerReview {
  id: string;
  cycle_id: string;
  reviewer_id: string;
  reviewee_id: string;
  ratings: {
    teamwork: number;         // 1-5
    communication: number;    // 1-5
    technical_skills: number; // 1-5
    reliability: number;      // 1-5
    helpfulness: number;      // 1-5
  };
  strengths: string[];
  areas_for_improvement: string[];
  specific_feedback: string;
  would_work_with_again: boolean;
  is_anonymous: boolean;
  submitted_at: string;
}

export interface PeerFeedbackSummary {
  reviewee_id: string;
  cycle_id: string;
  total_reviews: number;
  avg_ratings: {
    teamwork: number;
    communication: number;
    technical_skills: number;
    reliability: number;
    helpfulness: number;
  };
  common_strengths: string[];
  common_improvements: string[];
  overall_sentiment: 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE';
}
