
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Folder, ExternalLink, Search, Plus, Building2, Mail, Phone, Briefcase, X, ArrowUpDown, FileText, Edit, Save, User, Grid, List, FileDown, Trash2, MapPin, Hash, Star, MapPinCheck, Loader2 } from 'lucide-react';
import { Client, UserRole } from '../types';
import { useAuth } from '../context/AuthContext';
import { AuthService } from '../services/firebase';
import { AIService } from '../services/ai';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const ClientsPage: React.FC = () => {
    const { user } = useAuth();
    const navigate = useNavigate();
    const [clients, setClients] = useState<Client[]>([]);
    const [searchTerm, setSearchTerm] = useState('');

    // Sort State
    const [sortBy, setSortBy] = useState<'name' | 'code' | 'status'>('name');
    const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('asc');

    // View State
    const [viewMode, setViewMode] = useState<'GRID' | 'LIST'>('GRID');

    // Modal States
    const [isAddModalOpen, setIsAddModalOpen] = useState(false);
    const [selectedClient, setSelectedClient] = useState<Client | null>(null);
    const [isEditing, setIsEditing] = useState(false);

    // Forms
    const [newClient, setNewClient] = useState<Partial<Client>>({
        name: '', code: '', serviceType: 'Audit', folderLink: '', status: 'Active',
        email: '', phone: '', contactPerson: '', notes: '',
        category: 'B', industry: 'Trading', address: '', panNumber: ''
    });

    const [editForm, setEditForm] = useState<Partial<Client>>({});

    // Map Verification State
    const [isVerifyingAddr, setIsVerifyingAddr] = useState(false);
    const [verifiedMapLink, setVerifiedMapLink] = useState<string | undefined>(undefined);

    useEffect(() => {
        if (user) {
            if (user.role !== UserRole.ADMIN && user.role !== UserRole.MASTER_ADMIN) {
                navigate('/dashboard'); // Redirect non-admins
                return;
            }
            fetchClients();
        }
    }, [user]);

    const fetchClients = async () => {
        if (!user) return;
        const data = await AuthService.getAllClients();
        setClients(data);
    };

    // ... (Keep existing handlers for Add/Update/Sort/Export) ...
    const handleAddClient = async (e: React.FormEvent) => {
        e.preventDefault();
        const client: Client = {
            id: '', // Generated by Firestore
            name: newClient.name!,
            code: newClient.code || `CL-${Math.floor(Math.random() * 1000)}`,
            serviceType: newClient.serviceType as any,
            folderLink: newClient.folderLink || '#',
            status: newClient.status as any,
            email: newClient.email,
            phone: newClient.phone,
            contactPerson: newClient.contactPerson,
            notes: newClient.notes,
            category: newClient.category as any,
            industry: newClient.industry as any,
            address: newClient.address,
            panNumber: newClient.panNumber
        };

        await AuthService.addClient(client);
        fetchClients();
        setIsAddModalOpen(false);
        setNewClient({
            name: '', code: '', serviceType: 'Audit', folderLink: '', status: 'Active',
            email: '', phone: '', contactPerson: '', notes: '',
            category: 'B', industry: 'Trading', address: '', panNumber: ''
        });
        setVerifiedMapLink(undefined);
    };

    const handleUpdateClient = async () => {
        if (!selectedClient || !editForm) return;
        const updatedClient = { ...selectedClient, ...editForm } as Client;
        await AuthService.updateClient(updatedClient);
        fetchClients();
        setSelectedClient(updatedClient);
        setIsEditing(false);
    };

    const handleCardClick = (client: Client) => {
        setSelectedClient(client);
        setEditForm(client);
        setIsEditing(false);
        setVerifiedMapLink(undefined);
    };

    const verifyAddress = async (isEdit: boolean) => {
        const form = isEdit ? editForm : newClient;
        if (!form.name && !form.address) {
            alert("Please enter a client name or address to verify.");
            return;
        }

        const query = `${form.name} ${form.address || ''}`;
        setIsVerifyingAddr(true);
        setVerifiedMapLink(undefined);

        const result = await AIService.findLocationDetails(query);

        if (result.mapLink) {
            setVerifiedMapLink(result.mapLink);
        }

        const confirmUpdate = window.confirm(`Found Location: ${result.text}\n\nUpdate address field with this?`);
        if (confirmUpdate) {
            if (isEdit) {
                setEditForm({ ...editForm, address: result.text });
            } else {
                setNewClient({ ...newClient, address: result.text });
            }
        }
        setIsVerifyingAddr(false);
    };

    const toggleSort = (field: 'name' | 'code' | 'status') => {
        if (sortBy === field) {
            setSortOrder(sortOrder === 'asc' ? 'desc' : 'asc');
        } else {
            setSortBy(field);
            setSortOrder('asc');
        }
    };

    const exportCSV = () => {
        const letterhead = [
            ["R. Sapkota & Associates"],
            ["Mid-Baneshwor, Kathmandu"],
            ["Client Directory Report"],
            [`Generated: ${new Date().toLocaleDateString()}`],
            []
        ];

        const headers = ["Name", "Code", "Service", "Status", "Contact", "Email", "Category", "Industry"];
        const rows = clients.map(c => [
            `"${c.name}"`, c.code, c.serviceType, c.status, `"${c.contactPerson}"`, c.email || '', c.category || '-', c.industry || '-'
        ]);
        let csvContent = "data:text/csv;charset=utf-8,"
            + letterhead.map(e => e.join(",")).join("\n") + "\n"
            + headers.join(",") + "\n"
            + rows.map(e => e.join(",")).join("\n");

        const encodedUri = encodeURI(csvContent);
        const link = document.createElement("a");
        link.setAttribute("href", encodedUri);
        link.setAttribute("download", "RSA_Client_Directory.csv");
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

    const exportPDF = () => {
        const doc = new jsPDF();

        // -- Letterhead Design --
        doc.setFontSize(22);
        doc.setTextColor(37, 99, 235); // Brand Blue
        doc.setFont("helvetica", "bold");
        doc.text("R. Sapkota & Associates", 105, 15, { align: "center" });

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.setFont("helvetica", "normal");
        doc.text("Mid-Baneshwor, Kathmandu", 105, 22, { align: "center" });

        // Decorative Line
        doc.setDrawColor(37, 99, 235);
        doc.setLineWidth(0.5);
        doc.line(20, 28, 190, 28);

        doc.setFontSize(14);
        doc.setTextColor(0);
        doc.setFont("helvetica", "bold");
        doc.text("Client Directory", 14, 40);

        const tableColumn = ["Code", "Client Name", "Service", "Ind.", "Cat.", "Contact"];
        const tableRows = clients.map(c => [
            c.code, c.name, c.serviceType, c.industry || '-', c.category || '-', c.contactPerson || '-'
        ]);

        autoTable(doc, {
            head: [tableColumn],
            body: tableRows,
            startY: 45,
            theme: 'grid',
            headStyles: { fillColor: [37, 99, 235], textColor: 255 },
            alternateRowStyles: { fillColor: [240, 249, 255] },
            styles: { fontSize: 9 }
        });

        doc.save("RSA_Client_Directory.pdf");
    };

    const filteredClients = clients
        .filter(c =>
            c.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
            c.code.toLowerCase().includes(searchTerm.toLowerCase())
        )
        .sort((a, b) => {
            let compareA = a[sortBy] || '';
            let compareB = b[sortBy] || '';
            if (compareA < compareB) return sortOrder === 'asc' ? -1 : 1;
            if (compareA > compareB) return sortOrder === 'asc' ? 1 : -1;
            return 0;
        });

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex flex-col md:flex-row justify-between items-center gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-white font-heading">Client Directory</h1>
                    <p className="text-sm text-gray-400">Manage client profiles, categorization, and details</p>
                </div>
                <div className="flex items-center space-x-3">
                    {(user?.role === UserRole.ADMIN || user?.role === UserRole.MASTER_ADMIN) && (
                        <>
                            <div className="flex items-center space-x-2 bg-white/5 p-1 rounded-xl border border-white/10 mr-2">
                                <button onClick={exportCSV} className="p-2 hover:bg-white/10 rounded-lg text-gray-400 hover:text-white" title="Export CSV"><FileText size={18} /></button>
                                <button onClick={exportPDF} className="p-2 hover:bg-white/10 rounded-lg text-gray-400 hover:text-white" title="Export PDF"><FileDown size={18} /></button>
                            </div>
                            <button
                                onClick={() => setIsAddModalOpen(true)}
                                className="bg-brand-600 text-white px-6 py-2.5 rounded-xl text-sm font-medium hover:bg-brand-700 flex items-center shadow-lg shadow-brand-900/40 transition-all hover:-translate-y-0.5 border border-brand-500/30"
                            >
                                <Plus size={18} className="mr-2" /> Add New Client
                            </button>
                        </>
                    )}
                </div>
            </div>

            {/* Controls Bar */}
            <div className="flex flex-col md:flex-row gap-4 justify-between items-center glass-panel p-4 rounded-xl animate-fade-in">
                <div className="relative w-full md:w-96">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <Search className="text-gray-400" size={18} />
                    </div>
                    <input
                        type="text"
                        className="block w-full pl-10 pr-3 py-2 border border-white/10 rounded-lg leading-5 bg-navy-800/50 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-brand-500 focus:bg-navy-900 transition-all text-sm text-gray-100"
                        placeholder="Search by name or code..."
                        value={searchTerm}
                        onChange={(e) => setSearchTerm(e.target.value)}
                    />
                </div>

                <div className="flex items-center gap-4">
                    <div className="flex items-center space-x-2 text-sm text-gray-400">
                        <span className="font-medium mr-2 hidden sm:inline">Sort:</span>
                        <button onClick={() => toggleSort('name')} className={`px-3 py-1.5 rounded-md flex items-center transition-colors ${sortBy === 'name' ? 'bg-brand-600/30 text-brand-200' : 'hover:bg-white/5'}`}>
                            Name <ArrowUpDown size={14} className="ml-1 opacity-70" />
                        </button>
                        <button onClick={() => toggleSort('status')} className={`px-3 py-1.5 rounded-md flex items-center transition-colors ${sortBy === 'status' ? 'bg-brand-600/30 text-brand-200' : 'hover:bg-white/5'}`}>
                            Status <ArrowUpDown size={14} className="ml-1 opacity-70" />
                        </button>
                    </div>
                    <div className="flex items-center bg-white/5 p-1 rounded-lg border border-white/10">
                        <button onClick={() => setViewMode('GRID')} className={`p-1.5 rounded ${viewMode === 'GRID' ? 'bg-white/10 text-white' : 'text-gray-400'}`}>
                            <Grid size={16} />
                        </button>
                        <button onClick={() => setViewMode('LIST')} className={`p-1.5 rounded ${viewMode === 'LIST' ? 'bg-white/10 text-white' : 'text-gray-400'}`}>
                            <List size={16} />
                        </button>
                    </div>
                </div>
            </div>

            {/* Client List/Grid */}
            {filteredClients.length === 0 ? (
                <div className="glass-panel p-12 rounded-2xl border border-white/10 flex flex-col items-center justify-center text-center animate-fade-in">
                    <div className="w-20 h-20 bg-white/5 rounded-full flex items-center justify-center mb-6 border border-white/10">
                        <Building2 size={40} className="text-gray-500" />
                    </div>
                    <h3 className="text-xl font-bold text-white mb-2">No Clients Found</h3>
                    <p className="text-gray-400 max-w-md mb-8">
                        The client directory is currently empty. Add your first client to start managing profiles and tasks.
                    </p>
                    {(user?.role === UserRole.ADMIN || user?.role === UserRole.MASTER_ADMIN) && (
                        <button
                            onClick={() => setIsAddModalOpen(true)}
                            className="bg-brand-600 hover:bg-brand-500 text-white px-8 py-3 rounded-xl font-bold shadow-lg shadow-brand-900/40 transition-all transform hover:-translate-y-1"
                        >
                            <Plus size={20} className="inline mr-2" /> Add Your First Client
                        </button>
                    )}
                </div>
            ) : viewMode === 'GRID' ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {filteredClients.map((client, idx) => (
                        <div
                            key={client.id}
                            onClick={() => handleCardClick(client)}
                            className="glass-panel p-6 rounded-xl hover:border-brand-500/40 hover:bg-navy-700 transition-all duration-300 group relative overflow-hidden cursor-pointer animate-fade-in-up"
                            style={{ animationDelay: `${idx * 50}ms` }}
                        >
                            {/* Hover Glow Effect */}
                            <div className="absolute top-0 right-0 w-32 h-32 bg-brand-500/10 rounded-full blur-3xl opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none"></div>

                            <div className="flex items-start justify-between mb-4 relative z-10">
                                <div className="flex items-center space-x-4">
                                    <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-navy-700 to-navy-800 border border-white/10 flex items-center justify-center text-gray-300 group-hover:from-brand-600 group-hover:to-accent-purple group-hover:text-white transition-all duration-300 shadow-inner group-hover:shadow-lg group-hover:scale-110">
                                        <Building2 size={24} />
                                    </div>
                                    <div>
                                        <h3 className="text-lg font-bold text-gray-100 leading-tight mb-1 font-heading">{client.name}</h3>
                                        <div className="flex items-center space-x-2">
                                            <span className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-white/5 text-gray-400 font-mono border border-white/5">{client.code}</span>
                                            {client.category && <span className="text-[10px] bg-brand-500/20 text-brand-300 px-1.5 rounded border border-brand-500/20">Cat: {client.category}</span>}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="space-y-3 mb-6 relative z-10">
                                <div className="flex items-center text-sm text-gray-400">
                                    <Briefcase size={14} className="mr-2 opacity-70 text-brand-400" />
                                    <span>Service: <span className="font-medium text-gray-200">{client.serviceType}</span></span>
                                </div>
                                {client.industry && (
                                    <div className="flex items-center text-sm text-gray-400">
                                        <Building2 size={14} className="mr-2 opacity-70 text-brand-400" />
                                        <span>Sector: <span className="font-medium text-gray-200">{client.industry}</span></span>
                                    </div>
                                )}
                                <div className="flex items-center justify-between mt-4">
                                    <span className={`px-2.5 py-1 text-xs font-semibold rounded-full border ${client.status === 'Active' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' : 'bg-red-500/10 text-red-400 border-red-500/20'}`}>
                                        {client.status}
                                    </span>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            ) : (
                <div className="glass-panel rounded-xl overflow-hidden animate-fade-in-up">
                    <table className="w-full text-left text-sm text-gray-300">
                        <thead className="bg-navy-900/50 text-gray-400 font-semibold border-b border-white/10">
                            <tr>
                                <th className="px-6 py-4 font-heading">Client Name</th>
                                <th className="px-6 py-4 font-heading">Sector</th>
                                <th className="px-6 py-4 font-heading">Service</th>
                                <th className="px-6 py-4 font-heading">Cat</th>
                                <th className="px-6 py-4 font-heading">Status</th>
                                <th className="px-6 py-4 font-heading">Contact</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-white/5">
                            {filteredClients.map((client, idx) => (
                                <tr key={client.id} className="hover:bg-white/5 transition-colors cursor-pointer animate-fade-in-up" style={{ animationDelay: `${idx * 30}ms` }} onClick={() => handleCardClick(client)}>
                                    <td className="px-6 py-4 font-semibold text-white">{client.name}</td>
                                    <td className="px-6 py-4">{client.industry || '-'}</td>
                                    <td className="px-6 py-4">{client.serviceType}</td>
                                    <td className="px-6 py-4"><span className="font-bold text-gray-400">{client.category || '-'}</span></td>
                                    <td className="px-6 py-4">
                                        <span className={`px-2 py-1 rounded text-xs border ${client.status === 'Active' ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' : 'bg-red-500/10 text-red-400 border-red-500/20'}`}>
                                            {client.status}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4 text-xs text-gray-400">
                                        <div>{client.contactPerson}</div>
                                        <div className="text-[10px] opacity-70">{client.phone}</div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            )}

            {/* Add Client Modal */}
            {isAddModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-md p-4 animate-in fade-in zoom-in duration-200">
                    <div className="glass-modal rounded-2xl shadow-2xl w-full max-w-2xl overflow-hidden flex flex-col max-h-[90vh] border border-white/10">
                        <div className="px-6 py-4 border-b border-white/10 flex justify-between items-center bg-white/5">
                            <h3 className="text-lg font-bold text-white font-heading">Add New Client</h3>
                            <button onClick={() => setIsAddModalOpen(false)} className="text-gray-400 hover:text-white transition-colors"><X size={20} /></button>
                        </div>

                        <div className="p-6 overflow-y-auto">
                            <form onSubmit={handleAddClient} className="space-y-4">
                                <div className="grid grid-cols-2 gap-4">
                                    <div className="col-span-2">
                                        <label className="block text-sm font-medium text-gray-300 mb-1">Client Name *</label>
                                        <input required className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.name} onChange={(e) => setNewClient({ ...newClient, name: e.target.value })} />
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-gray-300 mb-1">Service Type</label>
                                        <select className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.serviceType} onChange={(e) => setNewClient({ ...newClient, serviceType: e.target.value as any })}>
                                            <option value="Audit">Audit</option>
                                            <option value="Tax">Tax</option>
                                            <option value="Accounting">Accounting</option>
                                            <option value="Consulting">Consulting</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-gray-300 mb-1">Status</label>
                                        <select className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.status} onChange={(e) => setNewClient({ ...newClient, status: e.target.value as any })}>
                                            <option value="Active">Active</option>
                                            <option value="Inactive">Inactive</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-gray-300 mb-1">Industry Sector</label>
                                        <select className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.industry} onChange={(e) => setNewClient({ ...newClient, industry: e.target.value as any })}>
                                            <option value="Hydropower">Hydropower</option>
                                            <option value="Manufacturing">Manufacturing</option>
                                            <option value="Trading">Trading</option>
                                            <option value="Consulting">Consulting</option>
                                            <option value="Security Broker">Security Broker</option>
                                            <option value="Other">Other</option>
                                        </select>
                                    </div>
                                    <div>
                                        <label className="block text-sm font-medium text-gray-300 mb-1">Categorization</label>
                                        <select className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.category} onChange={(e) => setNewClient({ ...newClient, category: e.target.value as any })}>
                                            <option value="A">Class A (High Value)</option>
                                            <option value="B">Class B (Medium)</option>
                                            <option value="C">Class C (Low)</option>
                                        </select>
                                    </div>
                                </div>

                                <div className="border-t border-white/10 pt-4">
                                    <h4 className="text-sm font-bold text-gray-400 mb-3 uppercase tracking-wide">Contact & Location</h4>
                                    <div className="grid grid-cols-2 gap-4">
                                        <div><label className="block text-xs text-gray-400 mb-1">Contact Person</label><input className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.contactPerson} onChange={(e) => setNewClient({ ...newClient, contactPerson: e.target.value })} /></div>
                                        <div><label className="block text-xs text-gray-400 mb-1">Phone Number</label><input className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.phone} onChange={(e) => setNewClient({ ...newClient, phone: e.target.value })} /></div>
                                        <div className="col-span-2"><label className="block text-xs text-gray-400 mb-1">Email</label><input type="email" className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.email} onChange={(e) => setNewClient({ ...newClient, email: e.target.value })} /></div>
                                        <div className="col-span-2 relative">
                                            <label className="block text-xs text-gray-400 mb-1">Address / Location</label>
                                            <div className="flex items-center space-x-2">
                                                <input className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.address} onChange={(e) => setNewClient({ ...newClient, address: e.target.value })} />
                                            </div>
                                            {verifiedMapLink && (
                                                <a href={verifiedMapLink} target="_blank" rel="noopener noreferrer" className="absolute right-14 top-8 text-[10px] text-brand-300 underline flex items-center bg-navy-900 px-1 rounded">
                                                    <ExternalLink size={10} className="mr-1" /> Map Link
                                                </a>
                                            )}
                                        </div>
                                        <div><label className="block text-xs text-gray-400 mb-1">PAN Number</label><input className="w-full glass-input rounded-lg px-3 py-2 text-sm" value={newClient.panNumber} onChange={(e) => setNewClient({ ...newClient, panNumber: e.target.value })} /></div>
                                    </div>
                                </div>

                                <div className="pt-2">
                                    <button type="submit" className="w-full bg-brand-600 text-white py-2.5 rounded-lg font-bold hover:bg-brand-700 transition-all transform hover:-translate-y-0.5 shadow-lg shadow-brand-900/40">
                                        Save Client
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            )}

            {/* Edit Modal Logic similar to Add Modal */}
            {selectedClient && (
                <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-md p-4 animate-in fade-in duration-200">
                    <div className="glass-modal rounded-2xl shadow-2xl w-full max-w-3xl overflow-hidden flex flex-col max-h-[90vh] border border-white/10">
                        <div className="px-8 py-6 bg-gradient-to-r from-navy-800 to-navy-900 border-b border-white/10 flex justify-between items-start">
                            <div className="flex-1 mr-4">
                                {isEditing ? (
                                    <input className="bg-black/20 text-2xl font-bold text-white px-2 py-1 rounded outline-none border border-white/20 w-full" value={editForm.name} onChange={(e) => setEditForm({ ...editForm, name: e.target.value })} />
                                ) : (
                                    <h2 className="text-2xl font-bold text-white font-heading">{selectedClient.name}</h2>
                                )}
                                <p className="text-brand-200 text-sm mt-1">{selectedClient.code} • {selectedClient.industry} • {selectedClient.address}</p>
                            </div>
                            <button onClick={() => setSelectedClient(null)} className="text-white/70 hover:text-white"><X size={24} /></button>
                        </div>

                        <div className="p-8 overflow-y-auto">
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                <div className="space-y-4">
                                    <h3 className="text-sm font-bold text-brand-400 uppercase tracking-wide">Client Details</h3>
                                    <div className="space-y-2">
                                        <p className="text-sm text-gray-400">Service: <span className="text-white">{isEditing ? <select value={editForm.serviceType} onChange={e => setEditForm({ ...editForm, serviceType: e.target.value as any })} className="bg-black/20 rounded p-1"><option value="Audit">Audit</option><option value="Tax">Tax</option></select> : selectedClient.serviceType}</span></p>
                                        <p className="text-sm text-gray-400">Status: <span className="text-white">{isEditing ? <select value={editForm.status} onChange={e => setEditForm({ ...editForm, status: e.target.value as any })} className="bg-black/20 rounded p-1"><option value="Active">Active</option><option value="Inactive">Inactive</option></select> : selectedClient.status}</span></p>
                                        <p className="text-sm text-gray-400">Category: <span className="text-white">{isEditing ? <select value={editForm.category} onChange={e => setEditForm({ ...editForm, category: e.target.value as any })} className="bg-black/20 rounded p-1"><option value="A">A</option><option value="B">B</option><option value="C">C</option></select> : selectedClient.category}</span></p>
                                    </div>
                                </div>
                                <div className="space-y-4">
                                    <h3 className="text-sm font-bold text-brand-400 uppercase tracking-wide">Contact Information</h3>
                                    <div className="space-y-2">
                                        <div className="flex items-center text-sm text-gray-300"><User size={14} className="mr-2 text-gray-500" /> {isEditing ? <input value={editForm.contactPerson} onChange={e => setEditForm({ ...editForm, contactPerson: e.target.value })} className="bg-black/20 rounded p-1 w-full" /> : selectedClient.contactPerson || 'N/A'}</div>
                                        <div className="flex items-center text-sm text-gray-300"><Phone size={14} className="mr-2 text-gray-500" /> {isEditing ? <input value={editForm.phone} onChange={e => setEditForm({ ...editForm, phone: e.target.value })} className="bg-black/20 rounded p-1 w-full" /> : selectedClient.phone || 'N/A'}</div>
                                        <div className="flex items-center text-sm text-gray-300"><Mail size={14} className="mr-2 text-gray-500" /> {isEditing ? <input value={editForm.email} onChange={e => setEditForm({ ...editForm, email: e.target.value })} className="bg-black/20 rounded p-1 w-full" /> : selectedClient.email || 'N/A'}</div>
                                        <div className="flex items-center text-sm text-gray-300 w-full relative">
                                            <MapPin size={14} className="mr-2 text-gray-500 flex-shrink-0" />
                                            {isEditing ? (
                                                <div className="flex items-center w-full space-x-2">
                                                    <input value={editForm.address} onChange={e => setEditForm({ ...editForm, address: e.target.value })} className="bg-black/20 rounded p-1 w-full" />
                                                </div>
                                            ) : (
                                                <span>
                                                    {selectedClient.address || 'N/A'}
                                                    {verifiedMapLink && <a href={verifiedMapLink} target="_blank" rel="noopener noreferrer" className="ml-2 text-xs text-brand-400 underline"><ExternalLink size={10} className="inline" /> Map</a>}
                                                </span>
                                            )}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div className="flex justify-end mt-8 border-t border-white/10 pt-6">
                                {(user?.role === UserRole.ADMIN || user?.role === UserRole.MASTER_ADMIN) && !isEditing && (
                                    <button onClick={() => setIsEditing(true)} className="text-brand-400 hover:text-brand-300 text-sm font-bold flex items-center transition-colors"><Edit size={16} className="mr-2" /> Edit Client</button>
                                )}
                                {isEditing && (
                                    <button onClick={handleUpdateClient} className="bg-emerald-600 hover:bg-emerald-500 text-white px-6 py-2 rounded-lg text-sm font-bold flex items-center shadow-lg shadow-emerald-900/40 transition-all transform hover:-translate-y-0.5"><Save size={16} className="mr-2" /> Save Changes</button>
                                )}
                            </div>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ClientsPage;
