
import React, { useState, useEffect } from 'react';
import { CalendarDays, CheckCircle, Clock, Plus, X, AlertCircle, Mail, XCircle, ChevronDown, Check, ThumbsDown, UserCog } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { LeaveRequest, UserRole } from '../types';
import { AuthService } from '../services/firebase';

const LeavePage: React.FC = () => {
  const { user } = useAuth();
  const [leaves, setLeaves] = useState<LeaveRequest[]>([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [newRequest, setNewRequest] = useState({
      type: 'Sick',
      startDate: '',
      endDate: '',
      reason: ''
  });

  useEffect(() => {
      if (user) loadLeaves();
  }, [user]);

  const loadLeaves = async () => {
      if (!user) return;
      // Admins see all, Staff sees own
      const userId = user.role === UserRole.ADMIN ? undefined : user.uid;
      const data = await AuthService.getAllLeaves(userId);
      setLeaves(data);
  };

  const handleSubmit = async (e: React.FormEvent) => {
      e.preventDefault();
      
      const request: LeaveRequest = {
          id: '', // Generated by service
          userId: user?.uid || 'unknown',
          userName: user?.displayName || 'User',
          type: newRequest.type as any,
          startDate: newRequest.startDate,
          endDate: newRequest.endDate,
          reason: newRequest.reason,
          status: 'PENDING',
          createdAt: new Date().toISOString().split('T')[0]
      };

      await AuthService.requestLeave(request);
      loadLeaves();
      setIsModalOpen(false);
      setNewRequest({ type: 'Sick', startDate: '', endDate: '', reason: '' });

      alert(`[SYSTEM]: Leave request submitted. Notification sent to Admin.`);
  };

  const handleStatusUpdate = async (id: string, status: 'APPROVED' | 'REJECTED') => {
      if (window.confirm(`Are you sure you want to ${status} this request?`)) {
          await AuthService.updateLeaveStatus(id, status);
          loadLeaves();
      }
  };

  const getStatusBadge = (status: string) => {
      switch(status) {
          case 'APPROVED': return <span className="flex items-center text-green-300 text-xs font-bold bg-green-500/20 border border-green-500/30 px-2 py-1 rounded-full w-fit"><CheckCircle size={12} className="mr-1" /> APPROVED</span>;
          case 'REJECTED': return <span className="flex items-center text-red-300 text-xs font-bold bg-red-500/20 border border-red-500/30 px-2 py-1 rounded-full w-fit"><XCircle size={12} className="mr-1" /> REJECTED</span>;
          default: return <span className="flex items-center text-amber-300 text-xs font-bold bg-amber-500/20 border border-amber-500/30 px-2 py-1 rounded-full w-fit"><Clock size={12} className="mr-1" /> PENDING</span>;
      }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
       <div className="flex justify-between items-center">
        <div>
            <h1 className="text-2xl font-bold text-white">Leave Management</h1>
            <p className="text-sm text-gray-400">Track balance and request time off</p>
        </div>
        <button 
            onClick={() => setIsModalOpen(true)}
            className="bg-blue-600 text-white px-4 py-2.5 rounded-xl text-sm font-medium hover:bg-blue-700 shadow-lg shadow-blue-900/40 flex items-center border border-blue-500/30 transition-all hover:-translate-y-0.5"
        >
            <Plus size={18} className="mr-2" /> Request Leave
        </button>
      </div>

      {/* Balance Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="glass-panel p-6 rounded-xl relative overflow-hidden group hover:bg-white/5 transition-all">
            <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <CalendarDays size={80} />
            </div>
            <div className="flex justify-between items-start relative z-10">
                <div>
                    <p className="text-sm font-medium text-gray-400">Annual Leave</p>
                    <h2 className="text-3xl font-bold text-white mt-2">12 <span className="text-sm font-normal text-gray-500">/ 20</span></h2>
                </div>
                <div className="p-2 bg-blue-500/20 text-blue-300 rounded-lg border border-blue-500/20"><CalendarDays size={20}/></div>
            </div>
            <div className="w-full bg-white/10 rounded-full h-1.5 mt-4">
                <div className="bg-blue-500 h-1.5 rounded-full shadow-[0_0_10px_rgba(59,130,246,0.5)]" style={{ width: '60%' }}></div>
            </div>
        </div>
        
        <div className="glass-panel p-6 rounded-xl relative overflow-hidden group hover:bg-white/5 transition-all">
             <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity text-red-500">
                <AlertCircle size={80} />
            </div>
             <div className="flex justify-between items-start relative z-10">
                <div>
                    <p className="text-sm font-medium text-gray-400">Sick Leave</p>
                    <h2 className="text-3xl font-bold text-white mt-2">5 <span className="text-sm font-normal text-gray-500">/ 10</span></h2>
                </div>
                <div className="p-2 bg-red-500/20 text-red-300 rounded-lg border border-red-500/20"><AlertCircle size={20}/></div>
            </div>
            <div className="w-full bg-white/10 rounded-full h-1.5 mt-4">
                <div className="bg-red-500 h-1.5 rounded-full shadow-[0_0_10px_rgba(239,68,68,0.5)]" style={{ width: '50%' }}></div>
            </div>
        </div>

         <div className="glass-panel p-6 rounded-xl relative overflow-hidden group hover:bg-white/5 transition-all">
             <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity text-amber-500">
                <Clock size={80} />
            </div>
             <div className="flex justify-between items-start relative z-10">
                <div>
                    <p className="text-sm font-medium text-gray-400">Pending Requests</p>
                    <h2 className="text-3xl font-bold text-amber-500 mt-2">{leaves.filter(l => l.status === 'PENDING').length}</h2>
                </div>
                <div className="p-2 bg-amber-500/20 text-amber-300 rounded-lg border border-amber-500/20"><Clock size={20}/></div>
            </div>
            <p className="text-xs text-gray-500 mt-4">Awaiting Admin Approval</p>
        </div>
      </div>

      {/* Leave History Table */}
      <div className="glass-panel rounded-xl overflow-hidden">
        <div className="px-6 py-4 border-b border-white/10 bg-white/5">
            <h3 className="font-bold text-white">Leave Requests & History</h3>
        </div>
        <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-gray-300">
                <thead>
                    <tr className="text-gray-400 border-b border-white/10 uppercase text-xs tracking-wider bg-black/20">
                        <th className="px-6 py-3 font-medium">Employee</th>
                        <th className="px-6 py-3 font-medium">Applied On</th>
                        <th className="px-6 py-3 font-medium">Type</th>
                        <th className="px-6 py-3 font-medium">Duration</th>
                        <th className="px-6 py-3 font-medium">Reason</th>
                        <th className="px-6 py-3 font-medium">Status</th>
                        {user?.role === UserRole.ADMIN && <th className="px-6 py-3 font-medium text-right">Actions</th>}
                    </tr>
                </thead>
                <tbody className="divide-y divide-white/5">
                    {leaves.map((leave) => (
                        <tr key={leave.id} className="hover:bg-white/5 transition-colors">
                            <td className="px-6 py-4 font-medium text-white">{leave.userName}</td>
                            <td className="px-6 py-4 text-gray-400 text-xs">
                                <div>{leave.createdAt}</div>
                            </td>
                            <td className="px-6 py-4 font-medium text-white">{leave.type}</td>
                            <td className="px-6 py-4 text-gray-300">
                                {leave.startDate === leave.endDate ? (
                                    <div>{leave.startDate}</div>
                                ) : (
                                    <div>
                                        <span>{leave.startDate} to {leave.endDate}</span>
                                    </div>
                                )}
                            </td>
                            <td className="px-6 py-4 text-gray-400 truncate max-w-xs">{leave.reason}</td>
                            <td className="px-6 py-4">
                                {getStatusBadge(leave.status)}
                            </td>
                            {user?.role === UserRole.ADMIN && (
                                <td className="px-6 py-4 text-right">
                                    {leave.status === 'PENDING' ? (
                                        leave.userId !== user.uid ? (
                                            <div className="flex justify-end space-x-2">
                                                <button onClick={() => handleStatusUpdate(leave.id, 'APPROVED')} className="p-1.5 bg-green-500/20 hover:bg-green-500/30 text-green-400 rounded-lg border border-green-500/20 transition-colors" title="Approve Request">
                                                    <Check size={16} />
                                                </button>
                                                <button onClick={() => handleStatusUpdate(leave.id, 'REJECTED')} className="p-1.5 bg-red-500/20 hover:bg-red-500/30 text-red-400 rounded-lg border border-red-500/20 transition-colors" title="Reject Request">
                                                    <X size={16} />
                                                </button>
                                            </div>
                                        ) : (
                                            <span className="inline-flex items-center px-2 py-1 rounded bg-gray-700/50 text-gray-400 text-[10px] border border-gray-600/30 cursor-help" title="You cannot approve your own request">
                                                <UserCog size={10} className="mr-1"/> Self Request
                                            </span>
                                        )
                                    ) : (
                                        <span className="text-xs text-gray-500 font-mono">
                                            {leave.status === 'APPROVED' ? 'Processed' : 'Closed'}
                                        </span>
                                    )}
                                </td>
                            )}
                        </tr>
                    ))}
                    {leaves.length === 0 && (
                        <tr>
                            <td colSpan={user?.role === UserRole.ADMIN ? 7 : 6} className="px-6 py-8 text-center text-gray-500">No leave history found.</td>
                        </tr>
                    )}
                </tbody>
            </table>
        </div>
      </div>

      {/* Request Modal */}
      {isModalOpen && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 animate-in fade-in zoom-in duration-200">
              <div className="glass-modal rounded-2xl shadow-2xl w-full max-w-md overflow-hidden transform transition-all scale-100 border border-white/10">
                  <div className="px-6 py-4 border-b border-white/10 flex justify-between items-center bg-white/5">
                      <h3 className="text-lg font-bold text-white">Request Leave</h3>
                      <button onClick={() => setIsModalOpen(false)} className="text-gray-400 hover:text-white transition-colors"><X size={20}/></button>
                  </div>
                  
                  <form onSubmit={handleSubmit} className="p-6 space-y-5">
                      <div className="relative">
                          <label className="block text-xs font-semibold text-gray-400 mb-1 uppercase tracking-wide">Leave Type</label>
                          <div className="relative">
                              <select 
                                className="w-full rounded-lg px-3 py-2.5 text-sm appearance-none cursor-pointer"
                                value={newRequest.type}
                                onChange={(e) => setNewRequest({...newRequest, type: e.target.value})}
                              >
                                  <option value="Sick">Sick Leave</option>
                                  <option value="Casual">Casual Leave</option>
                                  <option value="Annual">Annual Leave</option>
                                  <option value="Unpaid">Unpaid Leave</option>
                              </select>
                              <ChevronDown className="absolute right-3 top-3 text-gray-400 pointer-events-none" size={16} />
                          </div>
                      </div>

                      <div className="grid grid-cols-2 gap-4">
                          <div>
                              <label className="block text-xs font-semibold text-gray-400 mb-1 uppercase tracking-wide">Start Date</label>
                              <input 
                                type="date"
                                required
                                className="w-full rounded-lg px-3 py-2 text-sm"
                                value={newRequest.startDate}
                                onChange={(e) => setNewRequest({...newRequest, startDate: e.target.value})}
                              />
                          </div>
                          <div>
                              <label className="block text-xs font-semibold text-gray-400 mb-1 uppercase tracking-wide">End Date</label>
                              <input 
                                type="date"
                                required
                                className="w-full rounded-lg px-3 py-2 text-sm"
                                value={newRequest.endDate}
                                onChange={(e) => setNewRequest({...newRequest, endDate: e.target.value})}
                              />
                          </div>
                      </div>

                      <div>
                          <label className="block text-xs font-semibold text-gray-400 mb-1 uppercase tracking-wide">Reason</label>
                          <textarea 
                            required
                            rows={3}
                            placeholder="e.g. Not feeling well, Family emergency..."
                            className="w-full rounded-lg px-3 py-2 text-sm"
                            value={newRequest.reason}
                            onChange={(e) => setNewRequest({...newRequest, reason: e.target.value})}
                          />
                      </div>
                      
                      <div className="pt-2">
                          <button 
                            type="submit"
                            className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white py-3 rounded-xl font-bold shadow-lg shadow-blue-900/30 flex justify-center items-center transition-all transform active:scale-[0.98]"
                          >
                              <Mail size={16} className="mr-2" /> Submit Request
                          </button>
                      </div>
                  </form>
              </div>
          </div>
      )}
    </div>
  );
};

export default LeavePage;
